= Components

== Defining Components
In F Prime, the component is the basic unit of FSW function. An F Prime component is similar to a class in an object-oriented language. An F Prime FSW application is divided into several component instances, each of which instantiates a component. The component instances communicate by sending and receiving invocations on their ports.

In F Prime, there are three kinds of components: active, queued, and passive. An active component has a thread of control and a message queue. A queued component has a message queue, but no thread of control; control runs on another thread, such as a rate group thread. A passive component has no thread of control and no message queue; it is like a non-threaded function library.
9.1. Component Definitions

An FPP component definition defines an F Prime component. To write a component definition, you write the following:

* The component kind: one of active, passive, or queued.
* The keyword component.
* The name of the component.
* A sequence of component members enclosed in curly braces \{ …​ \}.
* As an example, here is a passive component C with no members:

----
@ An empty passive component
passive component C {

}
----

A component definition and each of its members is an annotatable element. For example, you can annotate the component as shown above. The members of a component form an element sequence with a semicolon as the optional terminating punctuation. The following sections describe the available component members.
