= Advanced Configuration

There are several advanced options users can consider while installing F'. However, users should be warned that some knowledge of our tools and versions is often required.

If you have recently started using F Prime, you can stop at this point. However, if you are seeking additional information regarding advanced CLI setup, please proceed to the next section.

== Installing Optional Components

Some F' packages contain optional components. These components can be installed by including the option in square brackets shown below:

[cols="1,1"]
|===
|Package|Description
|`fprime-tools[dev]`
|Installs the Python development tools for working with F' Python code

|`fprime-gds[uart-adapter]`
|Installs the UART communication adapter for the F' GDS

|`fprime-gds[test-api-xls]`
|Installs excel logging for use within the integration test framework
|===

CAUTION: These packages are optional as they pull in many additional packages and libraries. These may not be supported on all systems.
