= Bootstrapping the F' Development Environment

[TIP]
Many operating systems provide Python PIP packages through their package managers (e.g., apt, yum). However, it is often advised to avoid installing these packages at the system level and instead use PIP to install them in a https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/[virtual environment,role=resource,window=_blank]. The rationale behind this recommendation is that the Python package version offered by the operating system may not be the required version needed by the Python project. As a result, we recommend users to install F' into a virtual environment.

Example of setting up a virtual environment:

[source,bash]
----
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install --upgrade pip
$ pip install --upgrade setuptools
----

To start using F Prime you need to install `fprime-tools` which is a Python package containing tools to work with F'. To install the fprime-tools run the following command.

[source,bash]
----
$ pip install fprime-tools
----
