= Troubleshooting

== Common issues
Installing requirements on various systems can give rise to a range of problems. Here is a list of common issues that have been encountered in the past. If your particular problem is not listed below, you can always refer to the https://github.com/nasa/fprime/discussions[Discussions Forum,role=resource,window=_blank] for additional questions and answers.

=== fprime-util command not found

If the user is using a virtual environment and receives the 'command not found', the problem is likely caused by the environment not being sourced in a new terminal. Make sure to source the environment before running.

For example if the virual environment is installed in the home direcrtory of the user with the name fprime-venv it can be activated by running the following command in the shell terminal:

[source,bash]
$ source $HOME/fprime-venv/bin/activate

=== fpp-redirect-helper permission denied

Helper script 'fpp-redirect-helper' exited with reason: Permission denied error can occur when the helper-script `fprime/cmake/autocoder/fpp-wrapper/fpp-redirect-helper` loses its execution permission.

To verify that this is the case, change to the directory containing fpp-redirect-helper and verify that it is executable.

[source,bash]
----
$ cd fprime/cmake/autocoder/fpp-wrapper/
$ ls -l
----

If it is not executable, add the permission back.

[source,bash]
$ chmod 700 fpp-redirect-helper

=== Missing Python PIP on Ubuntu

Ubuntu and possibly other Debian variants don't include the pip packages in the default Python 3 installation. To get fully functional, use these commands on Ubuntu and Debian based systems:

[source,bash]
$ sudo apt install git cmake default-jre python3 python3-pip python3-venv

=== MacOS X and CMake Command Not Found

If the user chooses to install CMake directly from the CMake site (not using homebrew nor Mac Ports), then the CMake command-line tools must be added to the user's PATH or default system libraries. The quickest command to do that is:

[source,bash]
$ sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install

More information can be found https://stackoverflow.com/questions/30668601/installing-cmake-command-line-tools-on-a-mac[here,role=resource,window=_blank]

=== SSL Error with Python 3.7+ on MacOS

The version of openSSL bundled with Python 3.7+ requires access to MacOS's root certificates and user might encounter the following error:

----
Failed find expected download: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get  local issuer certificate
----

If the above error is encountered while installing F Prime run the following command in a macOS terminal to install necessary certificates:

[source,bash]
----
$ cd /Applications/Python\ 3.X/
$ ./Install\ Certificates.command
----

After the above command re-try to install F Prime.
